# Generated by Django 5.1.6 on 2025-03-02 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetrackapp.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
