# Generated by Django 5.1.6 on 2025-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0003_rename_category_id_budget_category_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
