# Generated by Django 5.1.6 on 2025-03-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0004_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
