# Generated by Django 5.1.6 on 2025-03-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0005_expense_expense_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
