# Generated by Django 5.1.6 on 2025-03-07 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0007_expense_created_at_expense_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_budget_user_category'),
        ),
    ]
