# Generated by Django 5.1.6 on 2025-03-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackapp', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
